<div id="shipping-method-delivery-date" class="add-delivery-date">
    <h3><?php echo $this->__('Add your requested delivery date'); ?></h3>
    <div class="fieldset">
        <ul>
            <li class="fields">
                <div class="field delivery-date">
                    <label for="sm-delivery-date"><?php echo $this->__('Enter Date:') ?></label>
                </div>
                <div class="input-box">
                    <input type="text" class="input-text" maxlength="255" title="Delivery date" value="" name="delivery_date" id="sm-delivery-date">
                </div>
            </li>
        </ul>
    </div>
</div>